version: "3"

services:
  dzz:
    build: .
    ports:
    - 8201:80
    env_file:
    - ./.env
    volumes:
    - ../casdoor_example/certs/tcub.site_ecc/ca.cer:/usr/local/share/ca-certificates/letsencrypt.crt
  db:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=HJdj23oid0
    - MYSQL_DATABASE=dzzoffice